# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 08:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recruitment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('current_designation', models.CharField(max_length=100)),
                ('current_employer', models.CharField(max_length=100)),
                ('current_ctc', models.PositiveIntegerField(blank=True)),
                ('expected_ctc', models.PositiveIntegerField(blank=True)),
                ('notice_period', models.PositiveIntegerField(blank=True)),
                ('total_exp_yrs', models.PositiveIntegerField()),
                ('total_exp_mts', models.PositiveIntegerField()),
                ('highest_qual', models.CharField(max_length=100)),
                ('college_highest_qual', models.CharField(max_length=100)),
                ('current_location', models.CharField(blank=True, max_length=100)),
                ('cv', models.FileField(upload_to=recruitment.models.get_upload_file_name)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted')], default='Pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('min_salary', models.PositiveIntegerField()),
                ('max_salary', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('min_requirement', models.TextField()),
                ('job_description', models.TextField()),
                ('posting_date', models.DateField(default=datetime.date.today)),
                ('about_company', models.TextField()),
            ],
            options={
                'ordering': ['-posting_date'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('cont_no', models.CharField(max_length=20)),
                ('job_description', models.TextField()),
                ('further_info', models.FileField(upload_to=recruitment.models.get_upload_file_name)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.JobOpening'),
        ),
    ]
